### ISSUE TITLE
[Feature] Support different screen sizes

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#365]
# Overview

[Android 12L introduces support for large screens](https://developer.android.com/about/versions/12/12L/summary#system-ui). Leveraging such a capability would be beneficial for users who use such large screens.

## Resources

- [Large screens landing page - Android Developers](https://developer.android.com/large-screens)
- [Support different screen sizes - Android Developers](https://developer.android.com/guide/topics/large-screens/support-different-screen-sizes)

## Todos

- [ ] Bump to Android 12L
- [ ] Test existing UI with Android 12L
- [ ] Update UI with large screens support
