### ISSUE TITLE
Decouple bottom app bar logic from `UiUtils`

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#492]
Decoupling the bottom app bar logic from `UiUtils` should hopefully make the code less brittle - for example, the FAB's `onClick` is sometimes not set when the fragment is resumed.

This is probably dependent on #456 and #347 as a pre-requisite

## Tasks

* [x] Remove `UiUtils` class
* [x] Move to shared activity `ViewModel`
* [x] Add method to show a snack-bar without requiring the `BottomAppBar`/`FloatingActionButton`
* [ ] Remove `BottomAppBar`/`FloatingActionButton` coupling entirely
* [ ] Migrate to Jetpack Compose (part of #368)
