### ISSUE TITLE
[Refactor] Migrate settings feature to Jetpack Compose

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#581]
(Sub-issue for #368)

## Tasks

* [ ] Add composables for preference list items
  * [x] Base composable
  * [x] Category group
  * [x] Two-state item (switch, checkbox)
  * [ ] Generic dialog preference
    * [ ] Input dialog (will need to revisit the API design)
    * [ ] List dialog (will need to revisit the API design)
* [ ] Migrate settings list screen to Compose
  * [x] Migrate to list-detail pattern (partially blocked until Material3 Adaptive gets Jetpack Navigation support, see [b/294612000](https://issuetracker.google.com/issues/294612000)
  * [ ] Migrate sub-pages
    * [x] Migrate general page (now appearance settings)
      * [ ] Move analytics settings to separate page
    * [x] Migrate tasks page
    * Migrate account page (tracked as part of account feature migration) - #585
    * [ ] #922
* [ ] Expose settings navigation graph (#456)

*(Last updated 3 Aug 2025)*
