### ISSUE TITLE
[Refactor] Rewrite tasks feature to Jetpack Compose

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#582]
Sub-issue for #368, tracking the tasks feature

## Tasks

* [ ] Migrate tasks screen to Compose
  * [ ] Use Compose variant of the options bottom sheet
* [ ] Add reusable TaskCard composable (WIP)
* [ ] Add composables for task item text-fields
* [ ] Expose tasks navigation graph (#456)
