### ISSUE TITLE
[Refactor] Rewrite main screen to Jetpack Compose

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#583]
Sub-issue for #368, tracking the main screen (`MainActivity`, the main entrypoint into the app)

## Tasks

* [ ] Add main screen composable (mostly done, not pushed yet)
  * [x] Use Material3 Adaptive `NavigationSuiteScaffold` (done, not pushed yet)
* [ ] Rewrite/remove shared FAB/BottomAppBar logic (see also #492)
* [ ] Hook up `SnackbarHostState` with `MainViewModel` to the screen composable
* [ ] Add `NavHost` for #456
* [ ] Remove `NavBottomSheetDialogFragment`
* [ ] Hook up dark theme/edge-to-edge/dynamic theme logic from appearance settings
* [ ] Remove existing fragment transactions logic once completely migrated
