### ISSUE TITLE
[Refactor] Migrate help feature to Jetpack Compose

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#584]
Sub-issue for #368, tracking the help feature (`features/help`)

## Tasks

* [ ] Rewrite help list screen to Compose
  * [x] Add reusable help article list item composable
  * [x] Remove `RecyclerView` adapter
* [ ] Add version dialog composable
* [ ] Expose help navigation graph (#456)
  * [ ] Remove old activity entrypoints (`HelpActivity`)
