### ISSUE TITLE
[Refactor] Migrate update screen to Jetpack Compose

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#586]
Sub-issue for #368, tracking the `UpdatesActivity` migration to Jetpack Compose

## Tasks

* [x] Migrate `UpdatesActivity` to use Fragments
* [ ] Migrate `UpdatesActivity` to Jetpack Compose (add screen composable)
  * [ ] Fix broken update logic (#386) 
  * [x] Remove duplicate check for updates logic (`SharedUtils#checkForUpdates` and `CheckForUpdatesWorker`)
* [ ] Expose updates navigation graph(?) (#456)
  * [ ] Remove `UpdatesActivity`
