### ISSUE TITLE
[Release] v1.0.0

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#6]
It's about time for an official release of v1.0.0! Here's some issues/PRs that need to be fixed/merged before releasing:
- [ ] #1 (optional) - Add calendar
- [ ] #2 - Implement a beta UI
- [ ] #3 - Better home page appearance (WIP)
- [x] #5 - Migrate to the new Cloud Firestore
- [x] #7 (optional) - New app icon design
- [x] Bottom navigation?

**Comment by EdricChan03** [comment]
Probably gonna skip straight to v1.1.0?
