### ISSUE TITLE
[Enhancement] Try out Kotlin Compose plugin introduced in 2.0.0-RC1

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#615]
[Kotlin 2.0.0-RC1](https://github.com/JetBrains/kotlin/releases/tag/v2.0.0-RC1) has merged the Compose plugin into the Kotlin repo, and is now published as a separate artifact - see [KT-67006](https://youtrack.jetbrains.com/issue/KT-67006 "Create new compose compiler Gradle plugin").

It can be consumed via the `org.jetbrains.kotlin.plugin.compose` plugin ID, and is available from [Gradle Plugin Portal](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.compose). [Configuration for the plugin can be found in the Kotlin repo](https://github.com/JetBrains/kotlin/blob/360343710f4ec0a8f9cd0dff39bd9a4f8917edd8/libraries/tools/kotlin-compose-compiler/src/common/kotlin/org/jetbrains/kotlin/compose/compiler/gradle/ComposeCompilerGradlePluginExtension.kt)

## Tasks

* [ ] Bump to Kotlin 2.0.0-RC1
* [ ] Add Compose plugin to `android-compose.gradle.kts` convention script
* [ ] Setup default plugin extension values if required
