### ISSUE TITLE
[Refactor] Remove `StudyBuddyCompatTheme` composable

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/studybuddy-android#808]
Accompanist's M2/M3/AppCompat ThemeAdapter library was recently removed in their [v0.37.0](https://github.com/google/accompanist/releases/tag/v0.37.0) release (and has been [deprecated since Aug 2023](https://medium.com/androiddevelopers/an-update-on-jetpack-compose-accompanist-libraries-august-2023-ac4cbbf059f1)), so we should also remove the compat `StudyBuddyCompatTheme` composable that is still present in the source:

https://github.com/EdricChan03/studybuddy-android/blob/a533e8ebc12f0c533f38da4e0ac03684ff4ab03a/ui/theming/compose/src/main/kotlin/com/edricchan/studybuddy/ui/theming/compose/StudyBuddyCompatTheme.kt#L1-L18

## Tasks

* [ ] Copy over existing XML theming (if necessary)
* [ ] Remove + update usages of `StudyBuddyCompatTheme` composable
* [ ] Remove ThemeAdapter library dependency
* [ ] Bump all Accompanist deps to 0.37.0
